### ISSUE TITLE
How use it?                                                                                                                                                                                                                                      deb: invalid option h                                                                                                                                                                                                                                                           user@amber ~/brotli-master $ ./deb --help deb: invalid option -help

### ISSUE THREAD

**Issue by alphaonex86** [madler/brotli#2]
Hello,
./deb -h  
deb: invalid option h  
./deb --help
deb: invalid option -help
How use it?

**Comment by madler** [comment]
deb is not meant for production use, so you would need to look in the source code to see how it works.  It is in the comment at the top:

`/* Decompress brotli streams on the command line or from stdin using yeast.
   The compressed output is written to the same name with the suffix ".bro" or
   ".compressed" removed and ".out" added, or to "deb.out" when reading from
   stdin. */`
