### ISSUE TITLE
status of br-format-v3.txt?

### ISSUE THREAD

**Issue by jason-sachs** [madler/brotli#4]
Hi -- I was wondering if you had any information on the status of https://github.com/madler/brotli/blob/master/br-format-v3.txt -- is it in use any prominent implementations besides in this repo?

I am getting started and the Google python package v1.0.9 (which includes an executable brotli.exe) does not appear to include any framing support.

If you don't know of any other prominent implementations that use it, could you give any recommendation on whether to use it or not? I would like to try using brotli in my Python application but not without some kind of minimal standard framing format that lets me identify the content as brotli vs. other compression types.

**Comment by jason-sachs** [comment]
(ref: https://github.com/google/brotli/issues/462)

**Comment by madler** [comment]
I have not kept track of the applications of brotli, so I don't know. Looks like you already have an issue up where I would go to ask this, https://github.com/google/brotli .

**Comment by jason-sachs** [comment]
ok, thanks, + thanks for making that proposal!

**Comment by madler** [comment]
You're welcome. The brotli guys asked me to make the proposal.
