### ISSUE TITLE
crc32 inline asm can be unsafe

### ISSUE THREAD

**Issue by justinliew** [madler/brotli#5]
Hi there!

I was using the Intel hardware `crc32c_hw` function from crc32c.c, and ran into a subtle reordering bug. I am unable to repro it in this repo, I think partly because of the pthread static init of the tables (we are explicitly initializing them on startup), but I was able to extract an example of it here: https://godbolt.org/z/7rb6KG1Kb

Here's a snippet of the relevant C portion that just does a single crc32q:
```
// the bytes we are trying to crc
const uint8_t bytes[8] = {1};
uint8_t *next = bytes;

// crc32 requires the dest to be preprocessed like this
crc0 = 0 ^ 0xffffffff;

// do a simple 64-bit (ie. qword) crc32 of the data in bytes, accumulating it in crc0
__asm__("crc32q\t" "(%1), %0"
    : "=r"(crc0)
    : "r"(next), "0"(crc0)
);

// post-process the final value
uint32_t crc = crc0 ^ 0xffffffff; 
```
You can see in the disassembly below that there's a possibility the `bytes` array gets reordered after the crc. This only happens in some situations; I was using -O3, and adding prints or other instructions around can change whether this happens or not. I was also only able to get this to happen on some versions of gcc; clang worked 100% of the time.

```
lea     rax, [rsp+8]           # this loads the address of bytes into rax
mov     esi, 4294967295.         # this is 0 ^ 0xffffffff, ie. crc0. esi is the lower 32-bits of rsi, which is used later
mov     edi, OFFSET FLAT:.LC0.         # loads the constant string for the printf below this
crc32q  (rax), rsi         # does a 64-bit CRC of the data pointed to by rax with rsi, accumulates into rsi
mov     QWORD PTR [rsp+8], 1         # moves the value 1 into the bytes array (!!)
not     esi # post-processses the result (ie. crc = crc0 ^ 0xffffffff )
```

The main issue is that the register constraint for the first param (`next` in my example) isn't correct. I believe this should be changed to a memory constraint and that fixes the issue.

```
__asm__("crc32q\t" "%1, %0"
    : "=r"(crc0)
    : "m"(*next), "0"(crc0)
);
```
The other option is to use intrinsics:
```
crc0 = _mm_crc32_u64(crc0, *(uint64_t *)next);
```
I am happy to make a PR for you for this if you're interested, but wasn't sure what your process was. The intrinsics change also requires SSE4.2 which means that it won't compile without changing some build/preprocessor stuff around.

Cheers,
Justin

**Comment by madler** [comment]
Thank you for the report. Please let me know if [this](https://github.com/madler/brotli/commit/46ecea69a993a7ebd2de4a60ae6042d31e26213f) fixes it.

**Comment by justinliew** [comment]
That fix does work - thank you. I might end up going with intrinsics in the end, but I know for a more general library, using them requires a bit more build and dependency handling, whereas fixing the inline asm is a much simpler fix.
Thank you for looking into this; I appreciate it and hopefully it helps others who use this in the future.

**Comment by kulikjak** [comment]
Hi, I am a little curious about this fix.

Is there a reason why this was fixed like this:
```C
        __asm__("crc32b\t" "(%1), %0"
                : "+r"(crc0)
                : "r"(next), "m"(*next));
```
rather than just:
```C
        __asm__("crc32b\t" "%1, %0"
                : "+r"(crc0)
                : "m"(*next));
```
When building this with Oracle Developer Studio (I was building memcached, which uses this code, on Solaris), the first version emits warnings:
```
"crc32c.c", line 175: warning: parameter in inline asm statement unused: %2
```
which makes sense as the `"m"(*next)` is one argument too many. And looking at the resulting assembly (from gcc) it generates additional instruction
```
crc32c_hw+0x3a:         48 8b 4d f0        movq   -0x10(%rbp),%rcx
```
result of which is then never used.

When compiled with `-O3`, the result is the same as the additional instruction is optimized out.

Thanks!

**Comment by madler** [comment]
@kulikjak You are correct. I will fix it.

**Comment by madler** [comment]
@kulikjak You're right about too many constraints, but your fix doesn't quite work. If the compiler decides to put a constant offset on the memory reference (which clang does as part of an optimization), then it just gets concatenated with the constant, e.g. `LONGx1`, which gives an incorrect offset and the code fails.

Just deleting the `, "m"(*next)` works, but then the compiler is deprived of optimizations of that pointer and the use of more indexing modes. I will look into a proper fix for this.

**Comment by madler** [comment]
@kulikjak In the meantime, I have pushed the fix that works.

**Comment by madler** [comment]
@kulikjak It's good now.

**Comment by kulikjak** [comment]
Thanks for the insight. I wasn't even sure whether it was a problem (I won't pretend I am an expert in inline assembly), but I was curious if it could be improved (to get rid of the Developer Studio warning) while keeping the optimization possibilities.

Anyway, thank you very much for the fix!
