### ISSUE TITLE
Alistair Moffat Sitemap or Index

### ISSUE THREAD

**Issue by MurageKibicho** [madler/brotli#7]
Good morning,
I hope this email finds you well. I saw you link to [Alistair Moffat's page](http://people.eng.unimelb.edu.au/ammoffat/inplace.c ) inside the file huff.c. It worked!

Out of curiosity, are there any other links to code he has written. I found his [Github](https://github.com/ammoffat) but he doesn't publish code. Thank you!

**Comment by madler** [comment]
Not that I know of. You could write him.

**Comment by madler** [comment]
You might find this useful: https://github.com/turpinandrew/shuff
